package cactividad03_programacion;
import java.awt.Color;
import java.util.Arrays;
import javax.swing.JOptionPane;

public class Funciones_Estadisticas extends javax.swing.JFrame {

    public Funciones_Estadisticas() {
        initComponents();
        formulario();
    }
  
    private void formulario(){
        this.setTitle("Funciones de Estadisticas de N Numeros");
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        this.getContentPane().setBackground(new Color(255, 255, 255));
        
    }
    
    private double calcularMedia(double[] datos) {
        double suma = 0;
        for (double dato : datos) {
            suma += dato;
        }
        return suma / datos.length;
    }
    
    private double calcularModa(double[] datos) {
        Arrays.sort(datos);
        int maxContador = 0;
        int contador = 1;
        double moda = datos[0];
        double actual = datos[0];

        for (int i = 1; i < datos.length; i++) {
            if (datos[i] == actual) {
                contador++;
            } else {
                if (contador > maxContador) {
                    maxContador = contador;
                    moda = actual;
                }
                contador = 1;
                actual = datos[i];
            }
        }

        if (contador > maxContador) {
            moda = actual;
        }

        return moda;
    }
    
    private double calcularMediana(double[] datos) {
        Arrays.sort(datos);
        if (datos.length % 2 == 0) {
            return (datos[datos.length / 2 - 1] + datos[datos.length / 2]) / 2;
        } else {
            return datos[datos.length / 2];
        }
    }
    
     private double calcularDesviacionEstandar(double[] datos) {
        double media = calcularMedia(datos);
        double suma = 0;
        for (double dato : datos) {
            suma += Math.pow(dato - media, 2);
        }
        return Math.sqrt(suma / datos.length);
    }
    
     private double calcularVarianza(double[] datos) {
        double media = calcularMedia(datos);
        double suma = 0;
        for (double dato : datos) {
            suma += Math.pow(dato - media, 2);
        }
        return suma / datos.length;
    }
    
    private double[] convertirCadenaADoubles(String entrada) {
        String[] partes = entrada.split(",");
        double[] datos = new double[partes.length];
        for (int i = 0; i < partes.length; i++) {
            datos[i] = Double.parseDouble(partes[i]);
        }
        return datos;
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelDigitarNum = new javax.swing.JPanel();
        txtNnumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEjemplo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaResultado = new javax.swing.JTextArea();
        panelOperaciones = new javax.swing.JPanel();
        ButtonCalcular = new javax.swing.JButton();
        ButtonNuevo = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDigitarNum.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setText("Digita los N Numeros:");

        txtEjemplo.setFont(new java.awt.Font("Segoe UI Historic", 2, 12)); // NOI18N
        txtEjemplo.setText("EJEMPLO: 4,5,7,8 CON COMAS");

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Funciones de Estadisticas de N Numeros");

        javax.swing.GroupLayout panelDigitarNumLayout = new javax.swing.GroupLayout(panelDigitarNum);
        panelDigitarNum.setLayout(panelDigitarNumLayout);
        panelDigitarNumLayout.setHorizontalGroup(
            panelDigitarNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDigitarNumLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelDigitarNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(panelDigitarNumLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDigitarNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDigitarNumLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtEjemplo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDigitarNumLayout.setVerticalGroup(
            panelDigitarNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDigitarNumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(panelDigitarNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEjemplo)
                .addGap(14, 14, 14))
        );

        panelDatos.setBackground(new java.awt.Color(204, 255, 204));

        textAreaResultado.setBackground(new java.awt.Color(204, 255, 204));
        textAreaResultado.setColumns(20);
        textAreaResultado.setRows(5);
        jScrollPane1.setViewportView(textAreaResultado);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        panelOperaciones.setBackground(new java.awt.Color(204, 255, 204));

        ButtonCalcular.setBackground(new java.awt.Color(204, 204, 255));
        ButtonCalcular.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        ButtonCalcular.setText("CALCULAR");
        ButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalcularActionPerformed(evt);
            }
        });

        ButtonNuevo.setBackground(new java.awt.Color(204, 204, 255));
        ButtonNuevo.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        ButtonNuevo.setText("NUEVO");
        ButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNuevoActionPerformed(evt);
            }
        });

        ButtonSalir.setBackground(new java.awt.Color(255, 102, 102));
        ButtonSalir.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        ButtonSalir.setText("SALIR");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOperacionesLayout = new javax.swing.GroupLayout(panelOperaciones);
        panelOperaciones.setLayout(panelOperacionesLayout);
        panelOperacionesLayout.setHorizontalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperacionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonCalcular, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelOperacionesLayout.setVerticalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ButtonCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonSalir)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDigitarNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDigitarNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalcularActionPerformed
    String entrada = txtNnumero.getText();
        
        // Convertir la entrada en un array de doubles
    double[] datos = convertirCadenaADoubles(entrada);

    // Calcular las estadísticas
    double media = calcularMedia(datos);
    double moda = calcularModa(datos);
    double mediana = calcularMediana(datos);
    double desviacionEstandar = calcularDesviacionEstandar(datos);
    double varianza = calcularVarianza(datos);
    
    // Mostrar los resultados en el JTextArea
    String resultados = 
                        "====RESULTADOS===="+ "\n" +
                        "Media: " + media + "\n" +
                        "Moda: " + moda + "\n" +
                        "Mediana: " + mediana + "\n" +
                        "Desviación Estándar: " + desviacionEstandar + "\n" +
                        "Varianza: " + varianza;
    textAreaResultado.setText(resultados);
    }//GEN-LAST:event_ButtonCalcularActionPerformed

    private void ButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNuevoActionPerformed
    //LIMPIA EL CAMPO DE ENTRADA
    txtNnumero.setText("");
    // LIMPIA EL AREA DE RESULTADO
    textAreaResultado.setText("");
    }//GEN-LAST:event_ButtonNuevoActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        int resp = JOptionPane.showOptionDialog(this,
                "Estas Seguro de Salir...",
                "Salida",JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Si" , "No"}, "Si");
        if (resp ==0) {
            System.exit(0);
        }
    }//GEN-LAST:event_ButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funciones_Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funciones_Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funciones_Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funciones_Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funciones_Estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCalcular;
    private javax.swing.JButton ButtonNuevo;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelDigitarNum;
    private javax.swing.JPanel panelOperaciones;
    private javax.swing.JTextArea textAreaResultado;
    private javax.swing.JLabel txtEjemplo;
    private javax.swing.JTextField txtNnumero;
    // End of variables declaration//GEN-END:variables
}
